// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controllers']['Category']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controllers']['Category']['Delete'](arg1);
}

export function ReadAll() {
  return window['go']['controllers']['Category']['ReadAll']();
}

export function ReadOne(arg1) {
  return window['go']['controllers']['Category']['ReadOne'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['controllers']['Category']['Update'](arg1, arg2);
}
