// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:string):Promise<{[key: string]: any}>;

export function Delete(arg1:string):Promise<{[key: string]: any}>;

export function ReadAll():Promise<Array<models.Category>>;

export function ReadOne(arg1:string):Promise<models.Category>;

export function Update(arg1:string,arg2:string):Promise<{[key: string]: any}>;
