// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {controllers} from '../models';

export function Create(arg1:models.Customer):Promise<{[key: string]: any}>;

export function Delete(arg1:string):Promise<{[key: string]: any}>;

export function ReadAll(arg1:controllers.CustomerSearchParams):Promise<Array<models.Customer>>;

export function ReadOne(arg1:string):Promise<models.Customer>;

export function Update(arg1:string,arg2:string):Promise<{[key: string]: any}>;
