// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controllers']['Customer']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controllers']['Customer']['Delete'](arg1);
}

export function ReadAll(arg1) {
  return window['go']['controllers']['Customer']['ReadAll'](arg1);
}

export function ReadOne(arg1) {
  return window['go']['controllers']['Customer']['ReadOne'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['controllers']['Customer']['Update'](arg1, arg2);
}
