// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['controllers']['General']['Activate'](arg1);
}

export function CheckActivation() {
  return window['go']['controllers']['General']['CheckActivation']();
}

export function CheckLogin() {
  return window['go']['controllers']['General']['CheckLogin']();
}

export function CreateAdmin(arg1) {
  return window['go']['controllers']['General']['CreateAdmin'](arg1);
}

export function GetActivationCode(arg1) {
  return window['go']['controllers']['General']['GetActivationCode'](arg1);
}

export function InstallationCode() {
  return window['go']['controllers']['General']['InstallationCode']();
}

export function Login(arg1) {
  return window['go']['controllers']['General']['Login'](arg1);
}

export function Setup(arg1) {
  return window['go']['controllers']['General']['Setup'](arg1);
}

export function StoreDetails() {
  return window['go']['controllers']['General']['StoreDetails']();
}

export function UpdateStore(arg1) {
  return window['go']['controllers']['General']['UpdateStore'](arg1);
}
