// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {controllers} from '../models';

export function Create(arg1:models.Product):Promise<{[key: string]: any}>;

export function Delete(arg1:string):Promise<{[key: string]: any}>;

export function FindByCode(arg1:string):Promise<models.Product>;

export function ReadAll(arg1:controllers.ProductSearchParams):Promise<Array<models.Product>>;

export function ReadOne(arg1:string):Promise<models.Product>;

export function Update(arg1:string,arg2:models.Product):Promise<{[key: string]: any}>;
