// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {controllers} from '../models';

export function Create(arg1:models.Sale):Promise<{[key: string]: any}>;

export function Delete(arg1:string):Promise<{[key: string]: any}>;

export function ReadAll(arg1:controllers.SalesSearch):Promise<Array<models.Sale>>;

export function ReadOne(arg1:string):Promise<models.Sale>;
