// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controllers']['Sales']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controllers']['Sales']['Delete'](arg1);
}

export function ReadAll(arg1) {
  return window['go']['controllers']['Sales']['ReadAll'](arg1);
}

export function ReadOne(arg1) {
  return window['go']['controllers']['Sales']['ReadOne'](arg1);
}
