// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';
import {models} from '../models';

export function Create(arg1:controllers.CreateStaffRequest):Promise<{[key: string]: any}>;

export function Delete(arg1:string):Promise<{[key: string]: any}>;

export function ReadOne(arg1:string):Promise<models.Staff>;

export function ReadProfile():Promise<models.Staff>;

export function Update(arg1:string,arg2:controllers.UpdateStaffRequest):Promise<{[key: string]: any}>;

export function UpdatePassword(arg1:controllers.UpdatePasswordRequest):Promise<{[key: string]: any}>;
