// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controllers']['Staff']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controllers']['Staff']['Delete'](arg1);
}

export function ReadAll(arg1) {
  return window['go']['controllers']['Staff']['ReadAll'](arg1);
}

export function ReadOne(arg1) {
  return window['go']['controllers']['Staff']['ReadOne'](arg1);
}

export function ReadProfile() {
  return window['go']['controllers']['Staff']['ReadProfile']();
}

export function Update(arg1, arg2) {
  return window['go']['controllers']['Staff']['Update'](arg1, arg2);
}

export function UpdatePassword(arg1) {
  return window['go']['controllers']['Staff']['UpdatePassword'](arg1);
}
